### ISSUE TITLE
PhpStorm64.exe + plugin 1.3 + Windows 7 x64

### ISSUE THREAD

**Issue by serbanghita** [bogdananton/PhpStorm-testNameGenerator#8]
The plugin keeps failing with this error. I'm running `PhpStorm64.exe` on Windows 7 x64 Home Premium.

When running `PhpStorm.exe` it works. I have the following shortcuts activated in `Keymap`: `Ctrl+Shift+U,U`, `Ctrl+Alt+L`, `Ctrl+Alt+U,U`. I'm using `Ctrl+Shift+U,U`

What seems to be the problem?

```
Plugin 'ro.bogdananton.testNameGenerator' failed to initialize and will be disabled.  Please restart PhpStorm.

com.intellij.diagnostic.PluginException: ro/bogdananton/testNameGenerator/BindKeymap : Unsupported major.minor version 51.0 [Plugin: ro.bogdananton.testNameGenerator]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:247)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:426)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:416)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:402)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:107)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:86)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:110)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:511)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:493)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:158)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:66)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:597)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:364)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: ro/bogdananton/testNameGenerator/BindKeymap : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:632)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:616)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:466)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:213)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:209)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:185)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 24 more

```

**Comment by serbanghita** [comment]
On `Win 8.1 pro x64` version `1.2` works having `Ctrl + Shift + U` as the default shortcut, my custom shortcuts are set just as above.
